# Generated by Django 4.0.4 on 2022-04-17 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_created_by_boxitem_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxitem',
            name='last_updated',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
    ]
