# Generated by Django 4.0.4 on 2022-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_boxitem_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxitem',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
