# Generated by Django 4.0.4 on 2022-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_boxitem_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxitem',
            name='creation_date',
            field=models.DateTimeField(default='2022-04-18T16:03:22.464493Z'),
        ),
    ]
