# Generated by Django 4.0.4 on 2022-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_boxitem_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.IntegerField(default=100)),
                ('V1', models.IntegerField(default=1000)),
                ('L1', models.IntegerField(default=100)),
                ('L2', models.IntegerField(default=50)),
            ],
        ),
        migrations.AlterField(
            model_name='boxitem',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
